service: hub-facecomparsion-api

provider:
  name: aws
  runtime: java21
  region: us-east-1
  apiName: ${self:service}-${self:custom.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:*
      Resource:
        - "*"

  environment:
    stage: ${self:custom.stage}
    region: ${aws:region} 
    service: ${self:service}

plugins:
  - serverless-manifest-plugin

custom:
  stage: ${sls:stage}
  product: youtube

package:
  artifact: app/target/facecomparsion-0.0.1-SNAPSHOT.jar

functions:
  app:
    handler: com.br.hub.facecomparsion.config.StreamLambdaHandler
    name: ${self:service}-${self:custom.stage}
    events:
    - http:
        cors: true
        path: '/facecomparsion/{proxy+}'
        method: any