service: hub-facecomparsion-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: java21
  region: us-east-1
  stage: ${opt:stage, 'prd'}
  apiName: ${self:service}-${self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:*
      Resource: "*"

  environment:
    stage: ${self:provider.stage}
    region: ${aws:region}
    service: ${self:service}

plugins:
  - serverless-manifest-plugin

package:
  artifact: target/facecomparsion-0.0.1-SNAPSHOT.jar

functions:
  app:
    handler: com.br.hub.facecomparsion.config.StreamLambdaHandler
    name: ${self:service}-${self:provider.stage}
    events:
      - http:
          path: facecomparsion/{proxy+}
          method: any
          cors: true