# Simple workflow for deploying static content to GitHub Pages
name: Deploy on AWS and GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  checks: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Maven install
        run: mvn --batch-mode clean install

      - name: Verify JAR exists
        run: |
          echo "Conteúdo da pasta target:"
          ls -lh target
          echo "Verificando se o JAR foi gerado..."
          test -f target/facecomparison-0.0.1-SNAPSHOT.jar

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: "target/facecomparsion-0.0.1-SNAPSHOT.jar"

  deployBackend:
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: aws
      url: ${{ steps.manifest.outputs.url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts
          path: app/target

      - name: Install Plugin and Deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless plugin install --name serverless-manifest-plugin && serverless deploy --stage prd"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: manifest
        id: manifest
        run: |
          url=$(cat .serverless/manifest.json | jq -r '.prd.urls.apiGateway')
          echo "::set-output name=url::$url"
    outputs:
      apiGatewayUrl: ${{ steps.manifest.outputs.url }}

  deployFrontend:
    needs: deployBackend
    environment:
      name: GH_PAGES_TOKEN
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Switch API URL in index.html
        run: |
          sed -i "s/\${URL_TO_SUBSTITUTE}/$(echo '${{ needs.deployBackend.outputs.apiGatewayUrl }}' | sed 's/\//\\\//g')/g" src/main/resources/static/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'src/main/resources/static/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
