# Simple workflow for deploying static content to GitHub Pages
name: Deploy on AWS and GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Verify JAR exists
        run: |
          ls -lh target
          test -f target/facecomparsion-0.0.1-SNAPSHOT.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: target/facecomparsion-0.0.1-SNAPSHOT.jar

  deployBackend:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts
          path: target

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Serverless Framework CLI
        run: npm install -g serverless@3.40.0

      - name: Deploy backend with Serverless
        run: serverless deploy --stage prd

      - name: Get API Gateway URL
        id: gateway
        run: |
          OUTPUT=$(serverless info --stage prd --verbose)
          echo "$OUTPUT"
          URL=$(echo "$OUTPUT" | grep -Eo 'https://[a-zA-Z0-9\-]+\.execute-api\.[a-z\-]+\.amazonaws\.com/prd')
          echo "api_url=$URL" >> $GITHUB_OUTPUT

 