# Simple workflow for deploying static content to GitHub Pages
name: Deploy on AWS and GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: target/facecomparsion-0.0.1-SNAPSHOT.jar

  deployBackend:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts
          path: target

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Serverless CLI v3
        run: npm install -g serverless@3

      - name: Deploy backend with Serverless
        working-directory: ./backend
        run: serverless deploy --stage prd