# Simple workflow for deploying static content to GitHub Pages
name: Deploy on AWS and GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Verify JAR exists
        run: |
          ls -lh target
          test -f target/facecomparsion-0.0.1-SNAPSHOT.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: target/facecomparsion-0.0.1-SNAPSHOT.jar

  deployBackend:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      SLS_ACCESS_TOKEN: ${{ secrets.SLS_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts
          path: target

      - name: Debug AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID set? ${AWS_ACCESS_KEY_ID:+yes}"
          echo "AWS_SECRET_ACCESS_KEY set? ${AWS_SECRET_ACCESS_KEY:+yes}"

      - name: Configure AWS credentials file
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

      - name: Install Serverless Framework CLI
        run: npm install -g serverless

      - name: Serverless Framework login
        run: serverless login --token $SLS_ACCESS_TOKEN

      - name: Install serverless-manifest-plugin and deploy
        run: |
          serverless plugin install --name serverless-manifest-plugin
          serverless deploy --stage prd

  deployFrontend:
    needs: deployBackend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Switch api URL in index.html
        run: |
          sed -i "s/\${URL_TO_SUBSTITUTE}/$(echo '${{ needs.deployBackend.outputs.apiGatewayUrl }}' | sed 's/\//\\\//g')/g" src/main/resources/static/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'src/main/resources/static/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
