# Simple workflow for deploying static content to GitHub Pages
name: Deploy on AWS and GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Verify JAR exists
        run: |
          ls -lh target
          test -f target/facecomparsion-0.0.1-SNAPSHOT.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: target/facecomparsion-0.0.1-SNAPSHOT.jar

  deployBackend:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts
          path: target

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Serverless Framework v3
        run: npm install -g serverless@3

      - name: Deploy using Serverless
        run: serverless deploy --stage prd

  deployFrontend:
    needs: deployBackend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Replace API URL in index.html (ajuste conforme necessário)
        run: |
          sed -i 's|${URL_TO_SUBSTITUTE}|https://seu-api-gateway-url.amazonaws.com/prd|' src/main/resources/static/index.html

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'src/main/resources/static/'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2