# Simple workflow for deploying static content to GitHub Pages
name: Deploy on AWS and GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Verify JAR exists
        run: |
          echo "Conteúdo da pasta target:"
          ls -lh target
          test -f target/facecomparsion-0.0.1-SNAPSHOT.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: target/facecomparsion-0.0.1-SNAPSHOT.jar

  deployBackend:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts
          path: target

      - name: Set Serverless access token
        run: echo "SERVERLESS_ACCESS_KEY=${{ secrets.SLS_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Install Serverless Framework CLI
        run: npm install -g serverless

      - name: Install serverless-manifest-plugin and deploy
        run: |
          serverless plugin install --name serverless-manifest-plugin
          serverless deploy --stage prd

  deployFrontend:
    needs: deployBackend
    environment:
      name: GH_PAGES_TOKEN
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Switch API URL in index.html
        run: |
          sed -i "s/\${URL_TO_SUBSTITUTE}/https:\/\/your-api-url.amazonaws.com\/prd\/facecomparsion/g" src/main/resources/static/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'src/main/resources/static/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2